### ISSUE TITLE
[feature request] Allow to stop the server

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-self-hosting#1]
See cozy/cozy-home#627

Request from @SeafireGit:

Could we get a "halt" button, next to "restart" ?
It would be useful for every user who get cozy self-hosted at home, and more user friendly than opening a ssh connection and shutting down every service.
As it could be blocking to stop a remote server, we could either enable this button by clicking a "self-hosted cosy" box, or put 5 advises to not click if we use a remote server.

Thanks and congrats for the job.
Seafire

**Comment by nledez** [comment]
Closed with https://github.com/cozy/cozy-self-hosting/pull/4

Thanks to @SomeAverageDev :)
